<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>uuid</key>
        <string>E07EC438-7B75-4437-8AA1-DA94C1E6EACC</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>name</key>
                <string>variable.language</string>
                <key>match</key>
                <string>\b(?:move|load|copy|save|iadd|isub|band|bior|bxor|call|exit|push|pull|brnz|bool)\b</string>
            </dict>
			<dict>
				<key>name</key>
				<string>keyword.other</string>
				<key>match</key>
				<string>\b(?:asm)\b</string>
			</dict>
            <dict>
                <key>name</key>
                <string>keyword.control</string>
                <key>match</key>
                <string>\b(?:if|else|for|while|return)\b</string>
            </dict>
			<!--
            <dict>
                <key>name</key>
                <string>keyword.control.conditional.haze</string>
                <key>match</key>
                <string>\b(?:if|else)\b</string>
            </dict>
			-->
			<dict>
				<key>name</key>
				<string>storage.type</string>
				<key>match</key>
				<string>\b(?:function|intrinsic|geometry)\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>keyword.operator</string>
				<key>match</key>
				<string>\b(?:r0|r1|r2|r3)\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>keyword.operator</string>
				<key>match</key>
				<string>\b(?:sky_color|mouse_sensitivity|fov)\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>entity.name.section</string>
				<key>match</key>
				<string>^\s*[a-zA-Z]+:</string>
			</dict>
			<dict>
				<key>name</key>
				<string>storage.type</string>
				<key>match</key>
				<string>\b(?:byte|nvr|float)\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>keyword.dotdir</string>
				<key>match</key>
				<string>^\s*(?:\.include|\.define|\.org|\.macro)\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>comment.line</string>
				<key>match</key>
				<string>;[^\n]+?$</string>
			</dict>
            <dict>
                <key>name</key>
                <string>keyword.operator</string>
                <key>match</key>
                <string>(?:;|\+|-|\*|=|\(|\)|\{|\})</string>
            </dict>
            <dict>
                <key>name</key>
                <string>comment.line</string>
                <key>match</key>
                <string>\/\/.*?$</string>
            </dict>
			<dict>
				<key>name</key>
				<string>constant.numeric</string>
				<key>match</key>
				<string>(?&lt;!\w)#[a-zA-Z0-9]+\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>constant.numeric</string>
				<key>match</key>
				<string>(?&lt;!\w)\$[a-zA-Z0-9]+\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>constant.numeric</string>
				<key>match</key>
				<string>(?&lt;!\w)&amp;[a-zA-Z0-9]+\b</string>
			</dict>
			<dict>
				<key>name</key>
				<string>constant.numeric</string>
				<key>match</key>
				<string>(?&lt;!\w)[0-9]+\b</string>
			</dict>
			<!--
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>variable.parameter.loop.begin.shell</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>variable.parameter.loop.haze</string>
                <key>match</key>
                <string>(?i)(%%)(~(?:f|d|p|n|x|s|a|t|z|\$[^:]*:)*)?[a-z]</string>
            </dict>
			-->
            <dict>
                <key>begin</key>
                <string>"</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.string.end</string>
                    </dict>
                </dict>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.string.begin</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.double</string>
                <key>end</key>
                <string>"|$</string>
            </dict>
        </array>
        <key>name</key>
        <string>Haze Source</string>
        <key>scopeName</key>
        <string>source.haze</string>
        <key>fileTypes</key>
        <array>
		  <string>hz</string>
		  <string>hzs</string>
		  <string>hzi</string>
        </array>
    </dict>
</plist>
